

## **A. Podstawy NumPy (Zadania 1–22)**



1. Utwórz tablicę liczb całkowitych od 0 do 19.  
   Następnie zmodyfikuj jej typ danych na float32.  
   Sprawdź minimalną i maksymalną wartość w tablicy.

In [3]:
import numpy as np

arr_np = np.arange(20)

arr_np = arr_np.astype(np.float32)

print(f'Min value: {np.min(arr_np)}')
print(f'Max value: {np.max(arr_np)}')

Min value: 0.0
Max value: 19.0


2. Skorzystaj z funkcji `linspace`, aby stworzyć tablicę 1D z 6 równomiernie rozmieszczonymi punktami w zakresie [0, 3].  
   Upewnij się, że liczba elementów zgadza się z parametrem `num`.


In [3]:
x = np.linspace(0,3,num=6)
print(x)

[0.  0.6 1.2 1.8 2.4 3. ]




3. Z tablicy liczb (np. 0–19) utwórz tablicę 2D o kształcie (4, 5) przy pomocy metody `reshape`.  
   Sprawdź nowy kształt (`.shape`) i liczbę wymiarów (`.ndim`).


In [5]:
tab = np.arange(20)
tab_multi_dim = tab.reshape((4,5))
print(f'{tab_multi_dim}\n')

print(f'Shape: {tab_multi_dim.shape}')
print(f'Dimension: {tab_multi_dim.ndim}')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Shape: (4, 5)
Dimension: 2


4. Rozszerz tablicę 2D (4×5) do wymiaru 3D (np. 2×2×5).  
   Następnie użyj `ravel()` i `flatten()`, aby spłaszczyć powstałą tablicę.  
   Zwróć uwagę, które z tych metod tworzą kopię, a które widok.

In [ ]:
tab_3d = tab_multi_dim.reshape((2,2,5))
print(f'Tab_3d:\n {tab_3d}\n')

x = tab_3d.flatten()
print(f'Flatten:\n {x}\n')
print(f'Tab_3d:\n {tab_3d}\n')
y = tab_3d.ravel()
print(f'Ravel:\n {y}\n')
print(f'Tab_3d:\n {tab_3d}\n')


Tab_3d: [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]

Flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Tab_3d: [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]

Ravel: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Tab_3d: [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]





5. Utwórz tablicę 1D z wartościami 10–19.  
   Wyświetl element o indeksie 0, element o indeksie 5 i element o indeksie -1.

In [70]:
tab = np.arange(10,20)
ind = [0,5,-1]
tab[ind]

array([10, 15, 19])

6. Stwórz tablicę 2D (5×5) z losowymi liczbami całkowitymi (`random.randint`).  
   Wybierz:
   - cały 2. wiersz (indeks 1),
   - 3 pierwsze kolumny wiersza 4 (indeks 3),
   - podtablicę (2×2) z górnego lewego rogu.

In [53]:
tab_2d = np.random.randint(10,size=(5,5))
print(tab_2d)
print(f'{tab_2d[1]}\n')             
print(f'{tab_2d[3, :3]}\n') 
print(f'{tab_2d[:2, :2]}')    


[[6 7 5 6 7]
 [4 0 4 2 3]
 [2 1 6 5 1]
 [8 0 8 6 8]
 [1 2 9 6 5]]
[4 0 4 2 3]

[8 0 8]

[[6 7]
 [4 0]]





7. Utwórz tablicę z wartościami `[0, 10, 20, 30, 40, 50]`.  
   Wybierz co drugi element, zaczynając od indeksu 1 (otrzymasz 10, 30, 50).


In [56]:
tab_x = np.arange(0,51,10)
print(tab_x)
print(f'{tab_x[1::2]}')

[ 0 10 20 30 40 50]
[10 30 50]




8. W tablicy 2D (5×5) ustaw cały 3. wiersz (indeks 2) na wartość 99.  
   Wyświetl zmodyfikowaną tablicę.

In [64]:
tab_y = np.random.randint(10, size = (5,5))
tab_yy = np.arange(25).reshape(5,5)
tab_zero = np.zeros((5,5))
print(f'{tab_y}\n')
print(f'{tab_yy}\n')
print(f'{tab_zero}\n')

tab_zero[2]=99

print(f'{tab_zero}\n')



[[6 7 3 6 4]
 [0 5 9 8 7]
 [8 2 2 8 6]
 [2 2 6 4 5]
 [8 8 1 3 8]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [99. 99. 99. 99. 99.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]





9. Korzystając z maski logicznej, wszystkie elementy < 10 w powyższej tablicy zastąp wartością 10.  
   Porównaj efekt z oryginałem.

In [66]:
tab_new = tab_yy.copy()
tab_new[tab_new<10] = 10

print(f'{tab_yy}\n')
print(f'{tab_new}\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]







10. Przytnij wszystkie wartości > 90 do poziomu 90 (można użyć maski lub funkcji `clip`).


In [69]:
tab_new_zero = tab_zero.copy()
tab_new_zero[tab_new_zero>90]=90
tab_new_clip = tab_new_zero.clip(0,90)

print(f'{tab_zero}\n')
print(f'{tab_new_zero}\n')
print(f'{tab_new_clip}\n')

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [99. 99. 99. 99. 99.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [90. 90. 90. 90. 90.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [90. 90. 90. 90. 90.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]



11. Stwórz tablicę 2D (3×3).  
    Dodaj nowy wiersz (3-elementowy) do jej końca, korzystając np. z funkcji `vstack`.  
    Wyświetl wynik.

In [75]:
tab_2d_3_3 = np.random.randint(20, size = (3,3))
print(f'{tab_2d_3_3}\n')
new_row = np.array([[1,2,3]])
print(f'{new_row}\n')

new_tab = np.vstack([tab_2d_3_3,new_row])
print(f'{new_tab}\n')


[[ 6 10  3]
 [10  4  0]
 [19  1  6]]

[[1 2 3]]

[[ 6 10  3]
 [10  4  0]
 [19  1  6]
 [ 1  2  3]]




12. Do powstałej tablicy dodaj nową kolumnę (4. kolumnę) za pomocą funkcji `hstack`.  
    Upewnij się, że nowa kolumna ma wymiar (4, 1), jeżeli tablica ma teraz 4 wiersze.


In [79]:
new_col = np.ones((4,1), dtype= int)
print(f'{new_col}\n')

new_tab_col = np.hstack([new_tab,new_col])
print(f'{new_tab_col}\n')


[[1]
 [1]
 [1]
 [1]]

[[ 6 10  3  1]
 [10  4  0  1]
 [19  1  6  1]
 [ 1  2  3  1]]



13. Użyj funkcji `delete`, aby usunąć 2. kolumnę (indeks 1).  
    Sprawdź kształt tablicy przed i po usunięciu.


In [87]:
deleted_col = np.delete(new_tab_col,1,axis=1)
print(f'{deleted_col}\n')

[[ 6  3  1]
 [10  0  1]
 [19  6  1]
 [ 1  3  1]]



14. Stwórz tablicę 2D (3×4) z liczbami od 1 do 12.  
    Policz sumę wszystkich elementów oraz sumy wzdłuż wierszy (axis=1) i wzdłuż kolumn (axis=0).

In [90]:
tab_3x4 = np.random.randint(12, size=(3,4))
print(f'{tab_3x4}\n')
print(f'Suma wzdłuż wierszy: {np.sum(tab_3x4,axis=1)}') 
print(f'Suma wzdłuż kolumn: {np.sum(tab_3x4, axis =0)}') 

[[ 2  6  4  1]
 [ 0  2  9 11]
 [ 4  1  4  7]]

Suma wzdłuż wierszy: [13 22 16]
Suma wzdłuż kolumn: [ 6  9 17 19]


15. Oblicz średnią (`mean`) i medianę (`median`) w tablicy 2D (np. (3×4) z poprzedniego zadania).  
    Porównaj wyniki.


In [94]:
print(f'Średnia: {np.mean(tab_3x4)}')
print(f'Mediana: {np.median(tab_3x4)}')

Średnia: 4.25
Mediana: 4.0


16. Napisz krótką funkcję (bez pętli), która w sposób wektorowy podniesie każdą wartość w tablicy 1D do kwadratu.


In [ ]:
def square_func():
    tab_square = np.arange(20)
    print(tab_square ** 2)

square_func()

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361]



17. Skorzystaj z `cumsum` (cumulative sum) i `cumprod` (cumulative product) na tablicy `[1, 2, 3, 4]`.  
    Wyświetl wyniki.

In [8]:
small_tab = np.arange(5)
print(f'{small_tab}\n')

cumsum_tab = np.cumsum(small_tab)
cumprod = np.cumprod(small_tab)

print(f'Cumsum tab:\n {cumsum_tab}\n')
print(f'Cumprod tab: \n {cumprod}\n')

[0 1 2 3 4]

Cumsum tab:
 [ 0  1  3  6 10]

Cumprod tab: 
 [0 0 0 0 0]




18. Wygeneruj tablicę 10 liczb losowych (typu float) w przedziale [0..1].  
    Oblicz odchylenie standardowe (`std`) oraz wariancję (`var`).

In [9]:
float_tab = np.random.rand(10)
print(f'{float_tab}\n')

std = np.std(float_tab)
var = np.var(float_tab)

print(f'Standard deviation: {std.round(2)}')
print(f'Variance: {var.round(2)}\n')

[0.90800173 0.02667525 0.57413813 0.56683194 0.62939916 0.4276311
 0.14074941 0.8821145  0.63678956 0.63192413]

Standard deviation: 0.27
Variance: 0.07




19. Stwórz tablicę 2D (3×3) oraz jednowymiarową (3 elementy).  
    Dodaj je do siebie, korzystając z mechanizmu broadcastingu.

In [20]:
tab1 = np.random.randint(20,size = (3,3))
tab2 = np.arange(10,31,10).reshape(3,1)

print(f'{tab1}\n')
print(f'{tab2}\n')

sum_tab = tab1+tab2

print(f'Sum of tables:\n {sum_tab}\n')


[[ 1 16  3]
 [ 1 13  6]
 [ 8 17 12]]

[[10]
 [20]
 [30]]

Sum of tables:
 [[11 26 13]
 [21 33 26]
 [38 47 42]]





20. Zademonstruj przypadek, w którym broadcasting się nie powiedzie (np. (3×3) + (2×3)).  
    Zaobserwuj komunikat o błędzie.

In [22]:
tab1 = np.random.randint(20,size = (3,3))
tab2 = np.random.randint(0,50,size=(3,4))

print(f'{tab1}\n')
print(f'{tab2}\n')

sum_tab = tab1+tab2

print(f'Sum of tables:\n {sum_tab}\n')


[[ 7 19 18]
 [14  8 14]
 [ 2  9  5]]

[[47 23 31 31]
 [21  6 19 27]
 [45 41 48 28]]



ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

21. Wygeneruj tablicę losową (8 elementów).  
    Użyj funkcji `where`, aby elementy < 0.5 zastąpić 0, a >= 0.5 zastąpić 1.  
    Wyświetl wynik.

In [ ]:
tab_8elemetns = np.arange(8)

22. Stwórz dwie tablice 1D (każda po 5 elementów).  
    Sklej je w jedną tablicę za pomocą `concatenate` i posortuj wynik za pomocą `sort`.

---

## **B. Dalsze Techniki NumPy (Zadania 23–29)**

23. Stwórz tablicę 2D (np. 100 wierszy, 3 kolumny) z losowymi wartościami float.  
    Policz korelację między kolumnami, korzystając z funkcji `corrcoef`.

24. W tej samej tablicy oblicz minimum, maksimum oraz kwartyle (funkcja `percentile` dla 25%, 50%, 75%).


25. Stwórz tablicę 2D (5×5) z losowymi liczbami.  
    Posortuj ją wzdłuż kolumn (parametr `axis=0`), np. korzystając z metody `sort`.




26. Podziel tablicę 1D (10 elementów) na dwie równe części, używając funkcji `split`.  
    Wyświetl obie części.


27. Załóż, że masz tablicę 1D (20 elementów).  
    Wybierz elementy mniejsze niż 5 **lub** większe niż 15, stosując złożoną maskę (np. `(arr < 5) | (arr > 15)`).


28. Użyj funkcji `clip`, aby przyciąć wartości w tej samej tablicy do przedziału [5..15].  
    Wyświetl efekt.


29. Stwórz dwie tablice 1D (każda po 5 elementów).  
    Sklej je (funkcja `concatenate`) i posortuj wynik (`sort`).  
    Porównaj z zadaniem 22, gdzie również występowało łączenie i sortowanie.


## **C. Zadania z Obrazami (Zadania 30–44)**


Mamy wczytane trzy obrazy  do tablic NumPy:  
- *The Persistence of Memory (1931)* – Salvador Dalí  
- *Flying Ship* – Zdzisław Beksiński  
- *Girl before a Mirror* – Pablo Picasso  

Każdy obraz to tablica o kształcie (wysokość, szerokość, kanały), np. `dali_img`, `beksinski_img`, `picasso_img`.



30. Wyświetl kształt (`shape`), liczbę kanałów (ostatni element `.shape`) i typ danych (`dtype`) w tablicach: `dali_img`, `beksinski_img`, `picasso_img`.


31. Za pomocą narzędzi do wykresów (np. `matplotlib.pyplot`) wyświetl wszystkie trzy obrazy obok siebie, używając funkcji `subplot`.  
    Dodaj tytuły, aby je rozróżnić.


32. Oblicz średnią wartość kanału R, G i B w obrazie Dalí.  
    Zdecyduj, który kanał ma największą średnią.

33. Sprawdź minimalną i maksymalną wartość pikseli (dla kanałów R, G, B) w obrazie Beksińskiego (np. metodami `.min()` i `.max()`).



34. Rozdziel obraz Picassa na trzy osobne tablice kanałów (R, G, B), używając indeksowania (np. `[..., 0]`).  
    Następnie zrekonstruuj oryginalny obraz przy pomocy `dstack` i wyświetl efekt.

35. Napisz funkcję `to_grayscale(img)`, która tworzy obraz w skali szarości według formuły `0.299*R + 0.587*G + 0.114*B`.  
    Zastosuj ją do obrazu Dalí i wyświetl wynik.



36. W obrazie Beksińskiego zwiększ intensywność kanału R o 20% i przytnij wartości do maksymalnego poziomu (np. 255).  
    Porównaj efekt z oryginałem.


37. Z obrazu Dalí wytnij fragment (np. `dali_img[50:300, 100:400, :]`) i wyświetl ten wykadrowany fragment.  
    Sprawdź nowy kształt tablicy.


38. Zmniejsz obraz Beksińskiego dwukrotnie w obu wymiarach, korzystając z indeksowania co 2 piksele .  
    Wyświetl pomniejszony obraz.


39. Odwróć obraz Picassa w poziomie (np. `flip` z parametrem `axis=1`).  
    Zapisz wynik do pliku `.npy` (funkcja `save`), a następnie wczytaj go ponownie (`load`), aby sprawdzić, czy zapis przebiegł poprawnie.




40. Obróć obraz Dalí o 90 stopni (np. w prawo), korzystając z `transpose` i ewentualnie `flip`.  
    Wyświetl wynik.


41. Skonwertuj obraz Beksińskiego do skali szarości (funkcja z zadania 35).  
    Następnie utwórz maskę logiczną dla pikseli, których jasność jest mniejsza niż 100,  
    i zamień te piksele w oryginalnym obrazie kolorowym na [0, 0, 255] (np. intensywny niebieski).




42. W obrazie Picassa przytnij wartości pikseli do zakresu [50..200], korzystając z `clip`.  
    Zaobserwuj zmianę kontrastu i wyświetl efekt.


43. Jeżeli Dalí i Beksiński mają różne rozmiary, przytnij któryś z nich, by dopasować wymiary (liczbę wierszy i kolumn).  
    Następnie sklej je w poziomie (`hstack`) i wyświetl otrzymany „dwupanelowy” obraz.

44. Wybierz dowolny przetworzony obraz (np. po filtrze, kadrowaniu lub maskowaniu) i zapisz go w formacie PNG (np. przy pomocy `imsave` z `matplotlib`).  
    Otwórz plik poza Pythonem, aby sprawdzić poprawność zapisu.